// <auto-generated />
namespace MeterReaderCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addleftcolumnanddeletetotalcolumnfrommeterreadertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addleftcolumnanddeletetotalcolumnfrommeterreadertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202209061023296_add left column and delete total column from meter reader table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
