// <auto-generated />
namespace MeterReaderCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createnotesbookstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createnotesbookstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202209051017443_create notes books table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
