// <auto-generated />
namespace MeterReaderCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changecalledandUncalledFieldsFromIntToDecimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changecalledandUncalledFieldsFromIntToDecimal));
        
        string IMigrationMetadata.Id
        {
            get { return "202209270841050_change called and Uncalled Fields From Int To Decimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
