// <auto-generated />
namespace MeterReaderCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addstreetnametonotebookstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstreetnametonotebookstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202211251142115_add street name to notebooks table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
