// <auto-generated />
namespace MeterReaderCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Changerelbetweentracksandnotebookstoonetomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changerelbetweentracksandnotebookstoonetomany));
        
        string IMigrationMetadata.Id
        {
            get { return "202309091041047_Change rel between tracks and notebooks to one to many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
